version: '3'

services:
  file-downloader:
    image: davis8988/file-downloader:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=DEBUG
      - SLEEP_BETWEEN_DOWNLOAD_TRIES_SECONDS=5
      - SRC_FILE_TO_DOWNLOAD_URL=https://raw.githubusercontent.com/Davis8988/birthday-dashboard/main/data/birthdays.csv
      - DEST_DOWNLOAD_DIR=/data
    volumes:
      - ./data:/data
